# Generated by Django 2.0.7 on 2018-08-07 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180807_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='write_date',
            field=models.DateField(auto_now=True),
        ),
    ]
